name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: '1.21'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        
    - name: Run tests
      run: make test
      
    - name: Build for multiple platforms
      run: |
        # Build for Linux
        GOOS=linux GOARCH=amd64 go build -o bin/citytimezones-linux-amd64 ./cmd/citytimezones
        GOOS=linux GOARCH=arm64 go build -o bin/citytimezones-linux-arm64 ./cmd/citytimezones
        
        # Build for macOS
        GOOS=darwin GOARCH=amd64 go build -o bin/citytimezones-darwin-amd64 ./cmd/citytimezones
        GOOS=darwin GOARCH=arm64 go build -o bin/citytimezones-darwin-arm64 ./cmd/citytimezones
        
        # Build for Windows
        GOOS=windows GOARCH=amd64 go build -o bin/citytimezones-windows-amd64.exe ./cmd/citytimezones
        GOOS=windows GOARCH=arm64 go build -o bin/citytimezones-windows-arm64.exe ./cmd/citytimezones
        
    - name: Create checksums
      run: |
        cd bin
        sha256sum * > checksums.txt
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}